---
abstract: 'Tapper - Context sensitive configuration hub for all Tapper libs'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Slurp: 0
  Tapper::Test: 3.000002
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Config
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::ShareDir: 0
  File::Slurp: 0
  Hash::Merge::Simple: 0
  YAML::Syck: 1.17
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Config
  repository: git://github.com/amd/Tapper-Config.git
version: 3.000004
